version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - movie-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - movie-network

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - movie-network

volumes:
  mongo-data:
networks:
  movie-network:
